from pwn import *
r = remote("cozen.challenges.ooo", 51015)

r.recv()
r.sendline("n")
r.recv()
r.sendline("n")
r.recv()
r.sendline("lmao")
r.recv()
r.sendline("lmao")
r.recv()
r.sendline("n")
r.recv()
r.sendline("c")
r.recv()
r.sendline("f")
r.recv()
r.sendline("5")
bind = r.recv()
print(bind)

for i in range(1,10):
    r.sendline(str(i))
    r.recvuntil("raw bytes for ")
    filename = r.recvuntil("\n").strip()
    data = r.recvuntil("==DONE== MD5")
    f = open(filename,"wb")
    f.write(data)
    f.close()
    print(filename)
# r.interactive()
